[2024-12-22T15:01:26.488+0000] {processor.py:186} INFO - Started process (PID=167) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:01:26.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:01:26.491+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:01:26.491+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:01:26.558+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:01:26.550+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 9, in <module>
    from src.dataset import main as generate_data
  File "/opt/airflow/src/__init__.py", line 1, in <module>
    from src import config  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/config.py", line 4, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
[2024-12-22T15:01:26.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:01:26.581+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.099 seconds
[2024-12-22T15:01:56.672+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:01:56.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:01:56.675+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:01:56.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:01:56.700+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:01:56.694+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 9, in <module>
    from src.dataset import main as generate_data
  File "/opt/airflow/src/__init__.py", line 1, in <module>
    from src import config  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/config.py", line 4, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
[2024-12-22T15:01:56.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:01:56.723+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.055 seconds
[2024-12-22T15:02:42.665+0000] {processor.py:186} INFO - Started process (PID=167) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:02:42.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:02:42.668+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:02:42.668+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:02:42.687+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:02:42.684+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 9, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:02:42.689+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:02:42.709+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.050 seconds
[2024-12-22T15:03:12.870+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:03:12.871+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:03:12.874+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:03:12.873+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:03:12.885+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:03:12.882+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 9, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:03:12.886+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:03:12.903+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.038 seconds
[2024-12-22T15:03:43.168+0000] {processor.py:186} INFO - Started process (PID=177) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:03:43.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:03:43.171+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:03:43.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:03:43.183+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:03:43.180+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 9, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:03:43.184+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:03:43.201+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.038 seconds
[2024-12-22T15:06:59.742+0000] {processor.py:186} INFO - Started process (PID=167) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:06:59.744+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:06:59.745+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:06:59.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:06:59.767+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:06:59.763+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:06:59.769+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:06:59.789+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.052 seconds
[2024-12-22T15:07:29.964+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:07:29.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:07:29.967+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:07:29.967+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:07:29.980+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:07:29.977+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:07:29.982+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:07:30.003+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.044 seconds
[2024-12-22T15:08:00.284+0000] {processor.py:186} INFO - Started process (PID=177) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:08:00.284+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:08:00.286+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:08:00.286+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:08:00.304+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:08:00.301+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:08:00.305+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:08:00.323+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.044 seconds
[2024-12-22T15:21:52.115+0000] {processor.py:186} INFO - Started process (PID=167) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:21:52.115+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:21:52.117+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:21:52.117+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:21:52.133+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:21:52.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:21:52.134+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:21:52.154+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.045 seconds
[2024-12-22T15:22:22.318+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:22:22.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:22:22.322+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:22:22.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:22:22.337+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:22:22.335+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:22:22.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:22:22.355+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.044 seconds
[2024-12-22T15:22:52.536+0000] {processor.py:186} INFO - Started process (PID=177) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:22:52.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:22:52.540+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:22:52.539+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:22:52.551+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:22:52.549+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:22:52.553+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:22:52.570+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.038 seconds
[2024-12-22T15:23:22.760+0000] {processor.py:186} INFO - Started process (PID=182) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:23:22.760+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:23:22.765+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:23:22.764+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:23:22.777+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:23:22.774+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:23:22.778+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:23:22.796+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.042 seconds
[2024-12-22T15:23:28.818+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:23:28.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:23:28.821+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:23:28.820+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:23:28.838+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:23:28.835+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:23:28.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:23:28.861+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.049 seconds
[2024-12-22T15:26:22.015+0000] {processor.py:186} INFO - Started process (PID=167) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:26:22.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:26:22.018+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:26:22.018+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:26:22.042+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:26:22.038+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:26:22.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:26:22.064+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.055 seconds
[2024-12-22T15:26:52.259+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:26:52.259+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:26:52.262+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:26:52.261+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:26:52.278+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:26:52.275+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:26:52.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:26:52.299+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.048 seconds
[2024-12-22T15:27:22.519+0000] {processor.py:186} INFO - Started process (PID=177) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:27:22.520+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:27:22.522+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:27:22.522+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:27:22.534+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:27:22.532+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:27:22.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:27:22.553+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.040 seconds
[2024-12-22T15:27:52.790+0000] {processor.py:186} INFO - Started process (PID=182) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:27:52.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:27:52.794+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:27:52.794+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:27:52.806+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:27:52.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:27:52.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:27:52.824+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.039 seconds
[2024-12-22T15:28:48.121+0000] {processor.py:186} INFO - Started process (PID=167) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:28:48.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:28:48.124+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:28:48.123+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:28:48.140+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:28:48.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:28:48.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:28:48.162+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.049 seconds
[2024-12-22T15:29:18.319+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:29:18.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:29:18.323+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:29:18.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:29:18.337+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:29:18.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:29:18.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:29:18.356+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.045 seconds
[2024-12-22T15:29:48.550+0000] {processor.py:186} INFO - Started process (PID=177) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:29:48.551+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:29:48.553+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:29:48.553+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:29:48.567+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:29:48.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:29:48.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:29:48.587+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.044 seconds
[2024-12-22T15:30:18.785+0000] {processor.py:186} INFO - Started process (PID=182) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:30:18.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:30:18.789+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:30:18.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:30:18.800+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:30:18.797+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:30:18.801+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:30:18.818+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.038 seconds
[2024-12-22T15:30:49.000+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:30:49.001+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:30:49.002+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:30:49.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:30:49.016+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:30:49.012+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:30:49.017+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:30:49.039+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.045 seconds
[2024-12-22T15:31:19.250+0000] {processor.py:186} INFO - Started process (PID=192) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:31:19.251+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:31:19.253+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:31:19.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:31:19.264+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:31:19.262+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:31:19.265+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:31:19.283+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.039 seconds
[2024-12-22T15:31:49.464+0000] {processor.py:186} INFO - Started process (PID=197) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:31:49.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:31:49.467+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:31:49.467+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:31:49.480+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:31:49.477+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:31:49.481+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:31:49.501+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.042 seconds
[2024-12-22T15:32:19.691+0000] {processor.py:186} INFO - Started process (PID=202) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:32:19.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:32:19.693+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:32:19.693+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:32:19.705+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:32:19.702+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:32:19.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:32:19.723+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.038 seconds
[2024-12-22T15:32:49.924+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:32:49.925+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:32:49.927+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:32:49.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:32:49.942+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:32:49.940+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:32:49.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:32:49.964+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.047 seconds
[2024-12-22T15:33:20.166+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:33:20.166+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:33:20.168+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:33:20.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:33:20.178+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:33:20.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:33:20.179+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:33:20.194+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.033 seconds
[2024-12-22T15:33:50.439+0000] {processor.py:186} INFO - Started process (PID=217) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:33:50.439+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:33:50.441+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:33:50.441+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:33:50.454+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:33:50.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:33:50.455+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:33:50.474+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.042 seconds
[2024-12-22T15:34:20.690+0000] {processor.py:186} INFO - Started process (PID=222) to work on /opt/airflow/src/dags/training.py
[2024-12-22T15:34:20.690+0000] {processor.py:914} INFO - Processing file /opt/airflow/src/dags/training.py for tasks to queue
[2024-12-22T15:34:20.692+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:34:20.692+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/src/dags/training.py
[2024-12-22T15:34:20.707+0000] {logging_mixin.py:190} INFO - [2024-12-22T15:34:20.704+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/src/dags/training.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/src/dags/training.py", line 15, in <module>
    from src.dataset import main as generate_data
ModuleNotFoundError: No module named 'src'
[2024-12-22T15:34:20.709+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/src/dags/training.py
[2024-12-22T15:34:20.727+0000] {processor.py:208} INFO - Processing /opt/airflow/src/dags/training.py took 0.044 seconds
